[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"

[[redirects]]
 from = "/*"
 to = "/public/index.html"
 status = 200

# [dev]
#     command = "npm run start"
#     targetPort = 3000
#     publish = "public"