[build]
  functions = "netlify/functions"
  publish = "build"

[functions]
  node_bundler = "esbuild"

[[redirects]]
 from = "/*"
 to = "/build/index.html"
 status = 200

[dev]
    command = "npm run start"
    targetPort = 3000
    publish = "public"